theme: jekyll-theme-hacker
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [The title of your site]
description: [A short description of your site's purpose]

show_downloads: [true]
google_analytics: [Your Google Analytics tracking ID]
